### ISSUE TITLE
Add props CustomClass for pass custom styling

### ISSUE THREAD

**Issue by mazipan** [alziqziq/vue-paginate-al#1]
Usually we use some class as root for adding custom style.
I think, will good for this thing to add feature passing customClass in parent of your component.

Thanks

**Comment by alziqziq** [comment]
I think it's not ready for now, but u can try like this :

// for default
 .pagination li a, .pagination li.disabled a{
    background: yellow;
    border-color: yellow;
    color: black;
  }

// for hover
  .pagination li a:hover, .pagination li.disabled a:hover {
    background: green;
    border-color: green;
    color: white;
  }

// for active
  .pagination .active a {
    background: black;
    border-color: black;
    color: white;    
  }
