### ISSUE TITLE
CSS needs to be scoped

### ISSUE THREAD

**Issue by malako** [alziqziq/vue-paginate-al#3]
It is messing up other parts of my page at the moment. Pls. use <style scoped></style>

EDIT: I see the CSS is scoped. The problem is that bootstrap is imported.

**Comment by nanborklabs** [comment]
has this issue been Resolved?

**Comment by ziqri-tiketcom** [comment]
sory for very very very slow respon :(

You can update to the latest version, i have added a scope.

enjoy.
@malako @nanborklabs

**Comment by alziqziq** [comment]
sorry for very very very slow respon :(

You can update to the latest version, i have added a scope.

enjoy.
@malako @nanborklabs

**Comment by malako** [comment]
Thanks
